services:
  phone_db:
    image: postgres:16-alpine
    container_name: phone_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - phone_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  phone-django:
    build: ..
    container_name: phone_django
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      phone_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ../apps/phone_info/management/data:/app/apps/phone_info/management/data:ro

volumes:
  phone_pg_data:
